# Generated by Django 3.2.24 on 2024-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_click'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Click',
        ),
    ]
